
#MO
spring.datasource.mo.jdbc-url=jdbc:mysql://localhost:3306/mo_demo
spring.datasource.mo.username=user_rep
spring.datasource.mo.password=1f24dd0f)Gn2!3kQ
spring.datasource.mo.driver-class-name=com.mysql.cj.jdbc.Driver


#DATAMART
spring.datasource.datamart.jdbc-url=jdbc:mysql://localhost:3306/db_datamart
spring.datasource.datamart.username=user_datamart
spring.datasource.datamart.password=0/OE6:rUbN_4t*
spring.datasource.datamart.driver-class-name=com.mysql.cj.jdbc.Driver


#EVENTOS
spring.datasource.wh.jdbc-url=jdbc:postgresql://localhost:5432/eventos_mo
spring.datasource.wh.username=uruben_view
spring.datasource.wh.password=2dQ1,2=v)@v0
spring.datasource.wh.driver-class-name=org.postgresql.Driver

#APP
job.cron.expression=0 0/5 * * * *
job.cron.reporte.colocacion=0 0/2 * * * *

excel.output.base-dir=/Users/luisantonioramirezfonseca/data/repo22
excel.template.path=/templates/data.xlsx
excel.template.path2=/templates/report.xlsx
excel.output.filename-prefix=reporte_liquidacion_
excel.output.filename-prefix2=reporte_colocacion_

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
