spring.datasource.mo.jdbc-url=jdbc:mysql://localhost:3306/mo
spring.datasource.mo.username=root
spring.datasource.mo.password=123
spring.datasource.mo.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.datamart.jdbc-url=jdbc:mysql://localhost:3306/datamart
spring.datasource.datamart.username=root
spring.datasource.datamart.password=123
spring.datasource.datamart.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.wh.jdbc-url=jdbc:postgresql://localhost:5432/wh_event
spring.datasource.wh.username=admin
spring.datasource.wh.password=123
spring.datasource.wh.driver-class-name=org.postgresql.Driver

#APP
job.cron.expression=0 0/5 * * * *

excel.output.path=/Users/luisantonioramirezfonseca/data/repo22/data.xlsx
excel.template.path=/templates/data.xlsx

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
